/************* sym.h **************/
#define symSYMMAX         25
#define symEOF             0
#define symerror           1
#define symIDENTIFIER      2
#define symNUMBER          3
#define symPLUS            4
#define symMINUS           5
#define symMUL             6
#define symDIV             7
#define symEQ              8
#define symEQUAL           9
#define symNEQ            10
#define symLESS           11
#define symLEQ            12
#define symGREATER        13
#define symGEQ            14
#define symLPAREN         15
#define symRPAREN         16
#define symSEMI           17
#define symPERIOD         18
#define symLBRACE         19
#define symRBRACE         20
#define symWHILE          21
#define symIF             22
#define symELSE           23
#define symPRINT          24
